"""
QARM Configuration File
=======================
Centralized configuration for all paths and parameters.
Modify the BASE_DIR if running on a different machine.
"""

from pathlib import Path

# =============================================================================
# BASE DIRECTORY - CHANGE THIS TO YOUR LOCAL PATH
# =============================================================================
# This is the only path you need to change when running on a different machine
BASE_DIR = Path(__file__).parent.resolve()

# =============================================================================
# DATA DIRECTORIES
# =============================================================================
DATA_DIR = BASE_DIR / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
PROCESSED_DATA_DIR = DATA_DIR / "processed"

# =============================================================================
# RAW DATA FILES (input data)
# =============================================================================
# StockTwits data - the main sentiment dataset
# Default location: data/raw/stocktwits_optimized.parquet
# Alternative: Abdul Stocktwits_10-07-2009_23-03-2020/stocktwits_optimized.parquet
STOCKTWITS_PARQUET = RAW_DATA_DIR / "stocktwits_optimized.parquet"

# Check if file exists in default location, otherwise use legacy location
_LEGACY_STOCKTWITS = BASE_DIR / "Abdul Stocktwits_10-07-2009_23-03-2020" / "stocktwits_optimized.parquet"
if not STOCKTWITS_PARQUET.exists() and _LEGACY_STOCKTWITS.exists():
    STOCKTWITS_PARQUET = _LEGACY_STOCKTWITS

# =============================================================================
# RAW PRICE DATA
# =============================================================================
# Cleaned prices file - stored in raw data as it's pre-processed input
PRICES_CLEANED_PARQUET = RAW_DATA_DIR / "prices_cleaned.parquet"

# Check for legacy location (in processed folder)
_LEGACY_PRICES = PROCESSED_DATA_DIR / "prices_cleaned.parquet"
if not PRICES_CLEANED_PARQUET.exists() and _LEGACY_PRICES.exists():
    PRICES_CLEANED_PARQUET = _LEGACY_PRICES

# =============================================================================
# PROCESSED DATA FILES (generated by optimization_old.py)
# =============================================================================
SENTIMENT_POLARITY_PARQUET = PROCESSED_DATA_DIR / "sentiment_polarity.parquet"
SP500_DATA_PARQUET = PROCESSED_DATA_DIR / "SP500_data.parquet"
RF_10_PARQUET = PROCESSED_DATA_DIR / "RF_10.parquet"

# Check for legacy locations (files in root QARM folder)
def _check_legacy_location(default_path: Path, filename: str) -> Path:
    """Check if file exists in legacy location (root folder)."""
    legacy_path = BASE_DIR / filename
    if not default_path.exists() and legacy_path.exists():
        return legacy_path
    return default_path

SENTIMENT_POLARITY_PARQUET = _check_legacy_location(SENTIMENT_POLARITY_PARQUET, "data/raw/sentiment_polarity.parquet")
SP500_DATA_PARQUET = _check_legacy_location(SP500_DATA_PARQUET, "data/raw/SP500_data.parquet")
RF_10_PARQUET = _check_legacy_location(RF_10_PARQUET, "data/raw/RF_10.parquet")

# =============================================================================
# MODEL PARAMETERS (defaults)
# =============================================================================
DEFAULT_LOOKBACK_DAYS = 180
DEFAULT_WINDOW_SENT = 30
DEFAULT_TOP_N = 50
DEFAULT_MAX_LONG = 0.25
DEFAULT_MAX_SHORT = 0.10
DEFAULT_Z_THRESHOLD = 0.5
DEFAULT_LAMBDA = 2.5  # Risk aversion

# =============================================================================
# DATE RANGE
# =============================================================================
DATA_START_DATE = "2009-01-01"
DATA_END_DATE = "2020-03-31"

# =============================================================================
# STOCK LIST FILE
# =============================================================================
STOCK_LIST_CSV = PROCESSED_DATA_DIR / "all_nyse_nasdaq_stocks_etfs.csv"

# =============================================================================
# HELPER FUNCTIONS
# =============================================================================
def ensure_directories():
    """Create all necessary directories if they don't exist."""
    for directory in [DATA_DIR, RAW_DATA_DIR, PROCESSED_DATA_DIR]:
        directory.mkdir(parents=True, exist_ok=True)

def get_path_str(path: Path) -> str:
    """Convert Path to string for libraries that don't support Path objects."""
    return str(path)

def check_data_files():
    """Check if required data files exist and return status."""
    files_status = {
        "stocktwits_raw": STOCKTWITS_PARQUET.exists(),
        "prices_cleaned": PRICES_CLEANED_PARQUET.exists(),
        "sentiment_polarity": SENTIMENT_POLARITY_PARQUET.exists(),
        "sp500_data": SP500_DATA_PARQUET.exists(),
        "stock_list": STOCK_LIST_CSV.exists(),
    }
    return files_status

def print_config():
    """Print current configuration for debugging."""
    print("=" * 60)
    print("QARM Configuration")
    print("=" * 60)
    print(f"Base Directory: {BASE_DIR}")
    print(f"Data Directory: {DATA_DIR}")
    print(f"Raw Data: {RAW_DATA_DIR}")
    print(f"Processed Data: {PROCESSED_DATA_DIR}")
    print("-" * 60)
    print("Data Files Status:")
    for name, exists in check_data_files().items():
        status = "✓" if exists else "✗"
        print(f"  {status} {name}")
    print("=" * 60)


if __name__ == "__main__":
    print_config()
